# Generated by Django 4.2.1 on 2023-05-26 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Datas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('phoneno', models.IntegerField()),
                ('mailid', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=250)),
                ('department', models.CharField(max_length=250)),
                ('course', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
                ('notebook', models.CharField(max_length=250)),
                ('pen', models.CharField(max_length=250)),
                ('record', models.CharField(max_length=250)),
                ('uniform', models.CharField(max_length=250)),
                ('exampaper', models.CharField(max_length=250)),
            ],
        ),
    ]
