# Generated by Django 4.2.1 on 2023-05-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='exampaper',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='datas',
            name='notebook',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='datas',
            name='pen',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='datas',
            name='record',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='datas',
            name='uniform',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
