# Generated by Django 4.2.1 on 2023-05-26 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_register', '0002_alter_datas_exampaper_alter_datas_notebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datas',
            name='exampaper',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='notebook',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='pen',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='record',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='datas',
            name='uniform',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
